# Generated by Django 4.2.6 on 2023-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority_alter_task_status_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High Priority'), ('M', 'Medium Priority'), ('L', 'Low Priority')], default='M', max_length=1),
        ),
    ]
